name: lusmart
description: "A new Flutter project for LU Smart system."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Application versioning
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2 # For picking images (e.g., facial data capture)
  cupertino_icons: ^1.0.8 # iOS-style icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # For recommended linting rules

flutter:
  uses-material-design: true # Enable Material Icons

  # Assets for the application
  assets:
    - assets/images/app_logo.png # Ensure your app logo is placed here
    - assets/images/ # Add more asset directories if needed
    - assets/user/user_profile.png

  # Custom fonts (optional, if needed)
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
